name: On push

on: push

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - run: yarn install
      - run: yarn test

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - run: yarn install
      - run: yarn lint

  docker:
    name: 'Smoke test production Docker image'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: docker compose -f docker-compose.production.yml up -d --build --wait
      - run: curl -Is http://localhost:3000/

  deploy:
    needs: [test, lint, docker]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    concurrency:
      group: deploy
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v6
      - uses: 12joan/build-and-push-image@main
